name: Test Self-Hosted Runner

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test-runner:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print runner info
        run: |
          echo "âœ… Self-hosted runner is working!"
          echo "ğŸ–¥ï¸ Hostname: $env:COMPUTERNAME"
          echo "ğŸ‘¤ Username: $env:USERNAME"
          echo "ğŸ“ Current directory: $(Get-Location)"
        shell: powershell

      - name: List files in repo
        run: |
          Get-ChildItem -Recurse
        shell: powershell

      - name: Simulate build step
        run: echo "ğŸ”§ Running build simulation..."





# name: Build and push Docker image to dockerhub

# on:
#   push:
#     branches: [ "master" ]



# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Check out the repo
#       uses: actions/checkout@v4

#     - name: Login to dockerhub
#       uses: docker/login-action@v3.1.0
#       with:
#        username: ${{ secrets.DOCKERHUB_NAME }}
#        password: ${{ secrets.DOCKERHUB_TOKEN }}

#     - name: Build and push to dockerhub
#       uses: docker/build-push-action@v5
#       with:
#        context:
#        push: true
#        tags: omiete01/webapp2:latest