name: Test Self-Hosted Runner

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test-runner:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print runner info
        shell: pwsh 
        run: |
          Write-Host "Self-hosted runner is working!"
          Write-Host "Hostname: $env:COMPUTERNAME"
          Write-Host "Username: $env:USERNAME"
          Write-Host "Current directory: $(Get-Location)"

      - name: List files in repo
        shell: pwsh
        run: |
          Get-ChildItem -Recurse

      - name: Simulate build step
        shell: pwsh
        run: Write-Host "ðŸ”§ Running build simulation..."


# name: Build and push Docker image to dockerhub

# on:
#   push:
#     branches: [ "master" ]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Check out the repo
#       uses: actions/checkout@v4

#     - name: Login to dockerhub
#       uses: docker/login-action@v3.1.0
#       with:
#        username: ${{ secrets.DOCKERHUB_NAME }}
#        password: ${{ secrets.DOCKERHUB_TOKEN }}

#     - name: Build and push to dockerhub
#       uses: docker/build-push-action@v5
#       with:
#        context:
#        push: true
#        tags: omiete01/webapp2:latest